// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/dizzrt/ellie"
	"github.com/dizzrt/ellie-layout/internal/application"
	"github.com/dizzrt/ellie-layout/internal/conf"
	"github.com/dizzrt/ellie-layout/internal/domain/example/biz"
	"github.com/dizzrt/ellie-layout/internal/handler"
	"github.com/dizzrt/ellie-layout/internal/infra/foundation"
	"github.com/dizzrt/ellie-layout/internal/server"
)

// Injectors from wire.go:

func wireApp() (*ellie.App, func(), error) {
	appConfig := conf.GetAppConfig()
	logWriter := foundation.NewLogger(appConfig)
	exampleBiz := biz.NewExampleBiz()
	exampleApplication := application.NewExampleApplication(exampleBiz)
	exampleHandler := handler.NewExampleHandler(exampleApplication)
	grpcServer := server.NewGRPCServer(appConfig, logWriter, exampleHandler)
	httpServer := server.NewHTTPServer(appConfig, logWriter, exampleHandler)
	app, cleanup, err := newApp(logWriter, grpcServer, httpServer)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
